def anamenu():
    print(100 * "_")
    print(34*"_" + "HALK KÜTÜPHANESİNE HOŞ GELDİNİZ" + 35*"_")
    print("_" + 98 * " " + "_")   
    print("_" + 98 * " " + "_")   
    print(100 * " ")      
    print(" 1- ÜYELİK İŞLEMLERİ ")
    print(" 2- KİTAP İŞLEMLERİ ") 
    print(" 3- ÇIKIŞ ") 
    print("_" + 98 * " " + "_")   
    print("_" + 98 * " " + "_")   
    print(100 * "_")


def kitapmenu():
    print(100 * "_")
    print(34*"_" + "KİTAP MENÜSÜ" + 35*"_")
    print(100 * " ")      
    print(100 * " ")   
    print(" 1- KİTAP LİSTESİ ")
    print(" 2- KİTAP EKLE ")
    print(" 3- KİTAP ARA ")
    print(" 4- KİTAP SİL ")
    print(" 5- ÜYEYE KİTAP VER ")   
    print(" 6- ANA MENÜYE DÖN ")    
    print(100 * " ")      
    print(100 * " ")      
    print(100 * "_")


def uyemenu():
    print(100 * "_")
    print(43*"_" + "ÜYELER MENÜSÜ" + 44*"_")
    print(100 * " ")      
    print(100 * " ")   
    print(" 1- ÜYE LİSTESİ ")
    print(" 2- ÜYE EKLE ")
    print(" 3- ÜYE ARA ")
    print(" 4- ÜYE GÜNCELLE ")    
    print(" 5- ÜYE SİL ")
    print(" 6- ÜYEYE KİTAP VER ")   
    print(" 7- KİTAP İADE ")       
    print(" 8- KİTAP TAKİBİ ")      
    print(" 9- ANA MENÜYE DÖN ")    
    print(100 * " ")      
    print(100 * " ")      
    print(100 * "_")